import {
  Business,
  BusinessMember,
  BusinessMemory,
  Customer,
  Lead,
  Product,
  ServiceItem,
  Order,
  Booking,
  Expense,
  DataSource,
  Automation,
  AgentAction,
  AIDiagnosis,
  AuditLog,
  Campaign,
} from '../types/database';

export const SEED_BUSINESS: Business = {
  id: 'biz_01_health_bengaluru',
  name: 'VedaVeda Ayurveda & Wellness',
  business_type: 'hybrid',
  industry: 'Health & Wellness',
  location: 'Indiranagar, Bengaluru',
  country: 'India',
  currency: 'INR',
  currency_symbol: '₹',
  timezone: 'Asia/Kolkata',
  business_age_stage: 'growing',
  data_maturity_mode: 'existing_partial',
  target_customers: 'Urban professionals (25-48 yrs) seeking authentic holistic health, stress relief, and herbal skincare',
  business_goals: [
    'Scale monthly revenue to ₹8,50,000',
    'Boost repeat consultation retention from 22% to 45%',
    'Automate WhatsApp lead follow-ups within 15 minutes',
    'Launch personalized seasonal herbal detox packages',
  ],
  monthly_revenue_target: 850000,
  created_at: '2025-01-15T08:00:00.000Z',
  updated_at: '2026-08-20T10:30:00.000Z',
};

export const SEED_MEMBERS: BusinessMember[] = [
  {
    id: 'mem_01',
    business_id: 'biz_01_health_bengaluru',
    user_id: 'usr_founder',
    role: 'owner',
    user_email: 'gajendravishwakarma738@gmail.com',
    user_name: 'Dr. Gajendra Vishwakarma',
    created_at: '2025-01-15T08:00:00.000Z',
  },
  {
    id: 'mem_02',
    business_id: 'biz_01_health_bengaluru',
    user_id: 'usr_ops',
    role: 'manager',
    user_email: 'priya.nair@vedaveda.in',
    user_name: 'Priya Nair (Clinic Ops)',
    created_at: '2025-03-10T09:00:00.000Z',
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod_01',
    business_id: 'biz_01_health_bengaluru',
    name: 'Brahmi & Ashwagandha Deep Sleep Elixir (100ml)',
    sku: 'VED-ELX-01',
    category: 'Formulations',
    price: 899,
    cost: 320,
    margin_pct: 64.4,
    stock_quantity: 42,
    status: 'active',
    total_sold: 168,
    created_at: '2025-02-01T10:00:00.000Z',
  },
  {
    id: 'prod_02',
    business_id: 'biz_01_health_bengaluru',
    name: 'Kumkumadi Radiance Face Oil (30ml)',
    sku: 'VED-OIL-02',
    category: 'Skincare',
    price: 1450,
    cost: 490,
    margin_pct: 66.2,
    stock_quantity: 18,
    status: 'active',
    total_sold: 214,
    created_at: '2025-02-01T10:00:00.000Z',
  },
  {
    id: 'prod_03',
    business_id: 'biz_01_health_bengaluru',
    name: 'Triphala Digestive Detox Powder (200g)',
    sku: 'VED-DTX-03',
    category: 'Formulations',
    price: 450,
    cost: 130,
    margin_pct: 71.1,
    stock_quantity: 6,
    status: 'low_stock',
    total_sold: 340,
    created_at: '2025-02-01T10:00:00.000Z',
  },
  {
    id: 'prod_04',
    business_id: 'biz_01_health_bengaluru',
    name: 'Organic Moringa & Wheatgrass Vitality Capsules (60ct)',
    sku: 'VED-CAP-04',
    category: 'Supplements',
    price: 699,
    cost: 210,
    margin_pct: 70.0,
    stock_quantity: 0,
    status: 'out_of_stock',
    total_sold: 95,
    created_at: '2025-04-10T10:00:00.000Z',
  },
];

export const SEED_SERVICES: ServiceItem[] = [
  {
    id: 'srv_01',
    business_id: 'biz_01_health_bengaluru',
    name: 'Prakriti Pulse Diagnosis & 1-on-1 Consultation',
    category: 'Consultation',
    duration_minutes: 45,
    price: 1200,
    status: 'active',
    bookings_count: 142,
    created_at: '2025-01-20T08:00:00.000Z',
  },
  {
    id: 'srv_02',
    business_id: 'biz_01_health_bengaluru',
    name: 'Abhyanga Herbal Body Therapy (60 Min)',
    category: 'Therapy',
    duration_minutes: 60,
    price: 2499,
    status: 'active',
    bookings_count: 88,
    created_at: '2025-01-20T08:00:00.000Z',
  },
  {
    id: 'srv_03',
    business_id: 'biz_01_health_bengaluru',
    name: 'Shirodhara Mind Stress Relief Ritual (75 Min)',
    category: 'Therapy',
    duration_minutes: 75,
    price: 3200,
    status: 'active',
    bookings_count: 64,
    created_at: '2025-01-20T08:00:00.000Z',
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust_01',
    business_id: 'biz_01_health_bengaluru',
    name: 'Ananya Sharma',
    email: 'ananya.sharma@techcorp.in',
    phone: '+91 98450 12844',
    city: 'Bengaluru',
    source: 'instagram',
    status: 'vip',
    first_seen: '2025-03-12T10:00:00.000Z',
    last_activity: '2026-08-18T14:20:00.000Z',
    total_orders: 8,
    total_spend: 21450,
    notes: 'Prefers weekend morning appointments. Uses Kumkumadi oil regularly.',
    tags: ['VIP', 'Skincare', 'Repeat'],
    created_at: '2025-03-12T10:00:00.000Z',
  },
  {
    id: 'cust_02',
    business_id: 'biz_01_health_bengaluru',
    name: 'Rahul K. Mehta',
    email: 'rahul.mehta@fintech.co',
    phone: '+91 98860 44912',
    city: 'Bengaluru',
    source: 'google_search',
    status: 'active',
    first_seen: '2025-06-04T12:00:00.000Z',
    last_activity: '2026-08-12T11:00:00.000Z',
    total_orders: 4,
    total_spend: 9600,
    notes: 'Consulted for chronic insomnia and stress management.',
    tags: ['Sleep Ritual', 'Consultation'],
    created_at: '2025-06-04T12:00:00.000Z',
  },
  {
    id: 'cust_03',
    business_id: 'biz_01_health_bengaluru',
    name: 'Divya Ranganathan',
    email: 'divya.r@outlook.com',
    phone: '+91 97401 88320',
    city: 'Mysuru',
    source: 'referral',
    status: 'churn_risk',
    first_seen: '2025-04-18T09:30:00.000Z',
    last_activity: '2026-05-10T16:00:00.000Z',
    total_orders: 2,
    total_spend: 3800,
    notes: 'Has not ordered in over 100 days. Needs win-back WhatsApp campaign.',
    tags: ['Win-back candidate'],
    created_at: '2025-04-18T09:30:00.000Z',
  },
  {
    id: 'cust_04',
    business_id: 'biz_01_health_bengaluru',
    name: 'Vikramaditya Rao',
    email: 'vikram.rao@venture.in',
    phone: '+91 99002 11980',
    city: 'Bengaluru',
    source: 'walk_in',
    status: 'repeat',
    first_seen: '2025-08-20T11:15:00.000Z',
    last_activity: '2026-08-21T18:00:00.000Z',
    total_orders: 5,
    total_spend: 14200,
    notes: 'Regular Shirodhara client on Friday evenings.',
    tags: ['Therapy', 'Indiranagar Local'],
    created_at: '2025-08-20T11:15:00.000Z',
  },
  {
    id: 'cust_05',
    business_id: 'biz_01_health_bengaluru',
    name: 'Sneha Patel',
    email: 'sneha.patel@designstudio.in',
    phone: '+91 96118 77234',
    city: 'Bengaluru',
    source: 'whatsapp',
    status: 'active',
    first_seen: '2026-01-10T14:00:00.000Z',
    last_activity: '2026-08-15T10:00:00.000Z',
    total_orders: 3,
    total_spend: 6450,
    notes: 'Interested in seasonal cleanse packs.',
    tags: ['Detox', 'WhatsApp Buyer'],
    created_at: '2026-01-10T14:00:00.000Z',
  },
];

export const SEED_LEADS: Lead[] = [
  {
    id: 'lead_01',
    business_id: 'biz_01_health_bengaluru',
    name: 'Kavita Sundaram',
    email: 'kavita.s@biocon.com',
    phone: '+91 98200 45112',
    source: 'Instagram Ad (Sleep Health)',
    status: 'new',
    score: 88,
    budget: 5000,
    interest_product_or_service: 'Prakriti Consultation + Sleep Elixir',
    last_follow_up: null,
    next_follow_up: '2026-08-25T11:00:00.000Z',
    notes: 'Submitted lead form 2 hours ago asking about pulse diagnosis slots.',
    converted_to_customer_id: null,
    created_at: '2026-08-24T18:30:00.000Z',
  },
  {
    id: 'lead_02',
    business_id: 'biz_01_health_bengaluru',
    name: 'Manish Chawla',
    email: 'manish.c@startup.in',
    phone: '+91 99800 77123',
    source: 'WhatsApp Inbound',
    status: 'contacted',
    score: 72,
    budget: 8000,
    interest_product_or_service: 'Corporate Wellness Package for 10 team members',
    last_follow_up: '2026-08-23T14:00:00.000Z',
    next_follow_up: '2026-08-26T15:00:00.000Z',
    notes: 'Requested brochure and pricing list for group Shirodhara sessions.',
    converted_to_customer_id: null,
    created_at: '2026-08-22T09:00:00.000Z',
  },
  {
    id: 'lead_03',
    business_id: 'biz_01_health_bengaluru',
    name: 'Pooja Hegde',
    email: 'pooja.hegde@gmail.com',
    phone: '+91 97312 90812',
    source: 'Google Search Local',
    status: 'qualified',
    score: 91,
    budget: 3500,
    interest_product_or_service: 'Kumkumadi Oil Combo + Face Ritual',
    last_follow_up: '2026-08-21T17:00:00.000Z',
    next_follow_up: '2026-08-25T10:30:00.000Z',
    notes: 'Ready to book for Saturday morning if slot is available.',
    converted_to_customer_id: null,
    created_at: '2026-08-20T11:00:00.000Z',
  },
  {
    id: 'lead_04',
    business_id: 'biz_01_health_bengaluru',
    name: 'Rohan Deshmukh',
    email: 'rohan.d@consulting.com',
    phone: '+91 96201 33400',
    source: 'Website Chat Widget',
    status: 'proposal_sent',
    score: 65,
    budget: 12000,
    interest_product_or_service: '3-Month Chronic Digestive Reset Program',
    last_follow_up: '2026-08-19T16:00:00.000Z',
    next_follow_up: '2026-08-27T12:00:00.000Z',
    notes: 'Sent diet protocol outline. Awaiting confirmation.',
    converted_to_customer_id: null,
    created_at: '2026-08-18T10:00:00.000Z',
  },
];

export const SEED_ORDERS: Order[] = [
  {
    id: 'ord_101',
    business_id: 'biz_01_health_bengaluru',
    customer_id: 'cust_01',
    customer_name: 'Ananya Sharma',
    items: [
      { id: 'prod_02', name: 'Kumkumadi Radiance Face Oil (30ml)', quantity: 2, unit_price: 1450, total: 2900 },
      { id: 'prod_01', name: 'Brahmi & Ashwagandha Deep Sleep Elixir', quantity: 1, unit_price: 899, total: 899 },
    ],
    total_amount: 3799,
    tax_amount: 190,
    discount_amount: 0,
    payment_status: 'paid',
    payment_method: 'upi',
    order_status: 'delivered',
    order_date: '2026-08-18T14:20:00.000Z',
    notes: 'Paid via GPay UPI ref: 4239810291.',
  },
  {
    id: 'ord_102',
    business_id: 'biz_01_health_bengaluru',
    customer_id: 'cust_04',
    customer_name: 'Vikramaditya Rao',
    items: [
      { id: 'prod_03', name: 'Triphala Digestive Detox Powder (200g)', quantity: 3, unit_price: 450, total: 1350 },
    ],
    total_amount: 1350,
    tax_amount: 67,
    discount_amount: 0,
    payment_status: 'paid',
    payment_method: 'card',
    order_status: 'delivered',
    order_date: '2026-08-21T18:00:00.000Z',
    notes: 'In-store POS card swipe.',
  },
  {
    id: 'ord_103',
    business_id: 'biz_01_health_bengaluru',
    customer_id: 'cust_05',
    customer_name: 'Sneha Patel',
    items: [
      { id: 'prod_01', name: 'Brahmi & Ashwagandha Deep Sleep Elixir', quantity: 2, unit_price: 899, total: 1798 },
      { id: 'prod_03', name: 'Triphala Digestive Detox Powder (200g)', quantity: 1, unit_price: 450, total: 450 },
    ],
    total_amount: 2248,
    tax_amount: 112,
    discount_amount: 100,
    payment_status: 'paid',
    payment_method: 'upi',
    order_status: 'processing',
    order_date: '2026-08-24T12:00:00.000Z',
    notes: 'WhatsApp order with 100 OFF coupon.',
  },
];

export const SEED_BOOKINGS: Booking[] = [
  {
    id: 'bk_201',
    business_id: 'biz_01_health_bengaluru',
    customer_id: 'cust_01',
    customer_name: 'Ananya Sharma',
    service_id: 'srv_03',
    service_name: 'Shirodhara Mind Stress Relief Ritual (75 Min)',
    booking_date: '2026-08-26',
    time_slot: '10:00 AM - 11:15 AM',
    status: 'confirmed',
    amount: 3200,
    payment_status: 'paid',
    notes: 'Room 2 (Lotus Suite) assigned.',
    created_at: '2026-08-22T10:00:00.000Z',
  },
  {
    id: 'bk_202',
    business_id: 'biz_01_health_bengaluru',
    customer_id: 'cust_02',
    customer_name: 'Rahul K. Mehta',
    service_id: 'srv_01',
    service_name: 'Prakriti Pulse Diagnosis & 1-on-1 Consultation',
    booking_date: '2026-08-27',
    time_slot: '04:00 PM - 04:45 PM',
    status: 'confirmed',
    amount: 1200,
    payment_status: 'pay_at_venue',
    notes: 'Follow-up sleep assessment.',
    created_at: '2026-08-23T11:30:00.000Z',
  },
];

export const SEED_EXPENSES: Expense[] = [
  {
    id: 'exp_01',
    business_id: 'biz_01_health_bengaluru',
    category: 'rent',
    title: 'Indiranagar Clinic Space Rent (August 2026)',
    amount: 75000,
    expense_date: '2026-08-01',
    payment_method: 'Net Banking (HDFC)',
    receipt_url: null,
    is_recurring: true,
    created_at: '2026-08-01T05:00:00.000Z',
  },
  {
    id: 'exp_02',
    business_id: 'biz_01_health_bengaluru',
    category: 'salaries',
    title: 'Staff & Therapist Salaries (3 Therapists + 1 Receptionist)',
    amount: 98000,
    expense_date: '2026-08-05',
    payment_method: 'Direct Bank Transfer',
    receipt_url: null,
    is_recurring: true,
    created_at: '2026-08-05T05:00:00.000Z',
  },
  {
    id: 'exp_03',
    business_id: 'biz_01_health_bengaluru',
    category: 'inventory',
    title: 'Organic Herbal Extracts & Kumkumadi Saffron Raw Batch',
    amount: 42000,
    expense_date: '2026-08-10',
    payment_method: 'UPI',
    receipt_url: null,
    is_recurring: false,
    created_at: '2026-08-10T08:00:00.000Z',
  },
  {
    id: 'exp_04',
    business_id: 'biz_01_health_bengaluru',
    category: 'marketing',
    title: 'Meta Instagram & Facebook Hyperlocal Ad Spend',
    amount: 24000,
    expense_date: '2026-08-15',
    payment_method: 'Credit Card',
    receipt_url: null,
    is_recurring: false,
    created_at: '2026-08-15T12:00:00.000Z',
  },
  {
    id: 'exp_05',
    business_id: 'biz_01_health_bengaluru',
    category: 'software_tools',
    title: 'WhatsApp Business API + CRM Billing Platform',
    amount: 4500,
    expense_date: '2026-08-16',
    payment_method: 'Card Auto-debit',
    receipt_url: null,
    is_recurring: true,
    created_at: '2026-08-16T04:00:00.000Z',
  },
];

export const SEED_MEMORY: BusinessMemory[] = [
  {
    id: 'mem_entry_01',
    business_id: 'biz_01_health_bengaluru',
    observation_type: 'baseline',
    period: 'day_0',
    title: 'Day 0 Foundation Baseline Established (Demo Seed)',
    content: 'Initial onboarding established core focus on premium wellness therapies and authentic classical formulations in Bengaluru. Target margin set at 65% for retail products.',
    confidence_score: 50,
    outcome_recorded: null,
    created_at: '2025-01-15T08:00:00.000Z',
    is_verified: false,
    provenance: {
      source_type: 'unverified_seed',
      has_sufficient_data: false,
      evidence_summary: 'Unverified demo seed. No underlying Supabase ledger records exist.',
    },
  },
  {
    id: 'mem_entry_02',
    business_id: 'biz_01_health_bengaluru',
    observation_type: 'customer_behavior',
    period: '90_day',
    title: 'Friday-Sunday Booking Velocity Spike (Demo Seed)',
    content: 'Synthetic pattern: 82% booking velocity spike claims require supporting 2025 booking transaction records in Supabase.',
    confidence_score: 30,
    outcome_recorded: null,
    created_at: '2025-05-10T10:00:00.000Z',
    is_verified: false,
    provenance: {
      source_type: 'unverified_seed',
      has_sufficient_data: false,
      evidence_summary: 'Insufficient data: No supporting 2025 booking transaction records in Supabase.',
    },
  },
  {
    id: 'mem_entry_03',
    business_id: 'biz_01_health_bengaluru',
    observation_type: 'metric_trend',
    period: '6_month',
    title: 'WhatsApp Channel Retention Observation (Demo Seed)',
    content: 'Synthetic pattern: WhatsApp vs Email retention comparison requires actual customer messaging logs and repeat order ledgers.',
    confidence_score: 30,
    outcome_recorded: null,
    created_at: '2025-08-15T14:00:00.000Z',
    is_verified: false,
    provenance: {
      source_type: 'unverified_seed',
      has_sufficient_data: false,
      evidence_summary: 'Insufficient data: No supporting email/messaging logs or repeat order ledgers in Supabase.',
    },
  },
];

export const SEED_AUTOMATIONS: Automation[] = [
  {
    id: 'auto_01',
    business_id: 'biz_01_health_bengaluru',
    name: 'Instant WhatsApp Welcome & Slot Booking for New Inbound Leads',
    trigger_type: 'new_lead',
    action_type: 'send_whatsapp',
    conditions: { source: 'all', delayMinutes: 2 },
    requires_approval: false,
    is_active: true,
    execution_count: 124,
    last_run: '2026-08-24T18:32:00.000Z',
  },
  {
    id: 'auto_02',
    business_id: 'biz_01_health_bengaluru',
    name: '45-Day Herbal Refill Reminder (Digestive & Sleep Formulations)',
    trigger_type: 'customer_reactivation_45d',
    action_type: 'send_whatsapp',
    conditions: { daysSinceLastOrder: 45, productCategories: ['Formulations', 'Supplements'] },
    requires_approval: true,
    is_active: true,
    execution_count: 58,
    last_run: '2026-08-22T09:00:00.000Z',
  },
  {
    id: 'auto_03',
    business_id: 'biz_01_health_bengaluru',
    name: 'Appointment Reminder 24h & 2h Before Therapy',
    trigger_type: 'booking_reminder',
    action_type: 'send_whatsapp',
    conditions: { hoursBeforeBooking: 24 },
    requires_approval: false,
    is_active: true,
    execution_count: 210,
    last_run: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'auto_04',
    business_id: 'biz_01_health_bengaluru',
    name: 'Low Stock Auto-Alert to Operations Manager (<10 units)',
    trigger_type: 'low_stock_alert',
    action_type: 'create_task',
    conditions: { thresholdUnits: 10 },
    requires_approval: false,
    is_active: true,
    execution_count: 14,
    last_run: '2026-08-23T16:00:00.000Z',
  },
];

export const SEED_AGENT_ACTIONS: AgentAction[] = [
  {
    id: 'act_01',
    business_id: 'biz_01_health_bengaluru',
    agent_name: 'Lead Follow-Up Agent',
    action_type: 'Send Personalized WhatsApp Follow-Up',
    target_entity: 'Lead: Kavita Sundaram (+91 98200 45112)',
    entity_id: 'lead_01',
    proposed_payload: {
      message: 'Namaste Kavita Ji! 🙏 Thank you for checking out VedaVeda. Dr. Gajendra has 2 slots available for Prakriti Pulse Diagnosis this Wednesday at 11 AM and Friday at 4 PM in Indiranagar. Would you like us to reserve one for you?',
      channel: 'WhatsApp',
      urgency: 'high',
    },
    status: 'pending_approval',
    impact_level: 'high',
    confidence: 94,
    reasoning: 'Inbound lead score is 88/100 and inquired specifically for sleep pulse diagnosis. Speed to reply under 3 hours increases conversion by 4.2x.',
    created_at: '2026-08-24T19:00:00.000Z',
    executed_at: null,
  },
  {
    id: 'act_02',
    business_id: 'biz_01_health_bengaluru',
    agent_name: 'Customer Assistant',
    action_type: 'Dormant Customer Win-back Offer',
    target_entity: 'Customer: Divya Ranganathan (+91 97401 88320)',
    entity_id: 'cust_03',
    proposed_payload: {
      message: 'Hello Divya! We missed you at VedaVeda. Dr. Gajendra has prepared our Monsoon Herbal Immunity package. Here is a special 15% VIP gratitude code: VEDA15 valid through Sunday.',
      channel: 'WhatsApp',
      discount_code: 'VEDA15',
    },
    status: 'pending_approval',
    impact_level: 'medium',
    confidence: 89,
    reasoning: 'Customer last engaged 106 days ago. Past spend of ₹3,800 indicates strong qualification; high probability of reactivation before complete churn.',
    created_at: '2026-08-24T15:30:00.000Z',
    executed_at: null,
  },
  {
    id: 'act_03',
    business_id: 'biz_01_health_bengaluru',
    agent_name: 'Business Analyst',
    action_type: 'Restock Purchase Order Notice',
    target_entity: 'Product: Triphala Digestive Detox (SKU: VED-DTX-03)',
    entity_id: 'prod_03',
    proposed_payload: {
      reorder_units: 150,
      estimated_stockout_days: 4,
      supplier: 'Kerala Herbal Co-op Batch #12',
    },
    status: 'approved',
    impact_level: 'high',
    confidence: 96,
    reasoning: 'Stock quantity down to 6 units. Top velocity SKU with 340 units sold. Stockout will leak an estimated ₹14,500/week in lost orders.',
    created_at: '2026-08-23T16:00:00.000Z',
    executed_at: '2026-08-23T17:15:00.000Z',
  },
];

export const SEED_DIAGNOSES: AIDiagnosis[] = [
  {
    id: 'diag_01',
    business_id: 'biz_01_health_bengaluru',
    problem_title: 'Low Weekday Capacity Utilization in Indiranagar Center',
    problem_description: 'Therapy rooms and practitioner hours are operating at only 32% capacity Monday through Thursday, compared to 94% on weekends, creating fixed rent and salary overhead waste.',
    category: 'operational',
    evidence: 'Booking records show 88 weekend appointments vs. only 24 weekday appointments over the last 60 days. Fixed monthly overhead of ₹1,73,000 (Rent + Salaries) is under-leveraged.',
    confidence: 94,
    severity: 'warning',
    recommended_action: 'Introduce "Weekday Workday Refresh" 45-minute Shirodhara packages targeted at local Indiranagar and Koramangala IT professionals with 20% off between 11 AM - 3 PM.',
    expected_kpi: '+₹1,15,000 monthly revenue from currently idle hours',
    effort: 'quick_win',
    status: 'open',
    created_at: '2026-08-20T10:00:00.000Z',
  },
  {
    id: 'diag_02',
    business_id: 'biz_01_health_bengaluru',
    problem_title: 'Uncaptured Repeat Refill Demand on Classical Formulations',
    problem_description: '74% of buyers of sleep and digestive formulations do not receive an automated refill notification when their 30-day bottle finishes, allowing them to purchase generic alternatives from Amazon or local chemists.',
    category: 'retention',
    evidence: 'Triphala Powder (340 sold) and Sleep Elixir (168 sold) show only a 22% 60-day repeat purchase rate, despite 94% customer satisfaction feedback.',
    confidence: 91,
    severity: 'critical',
    recommended_action: 'Activate automated WhatsApp replenishment triggers at Day 25 post-delivery with 1-click UPI reorder links and free herbal tea sampler bonus.',
    expected_kpi: 'Increase repeat customer rate from 22% to 48% within 60 days',
    effort: 'quick_win',
    status: 'open',
    created_at: '2026-08-21T11:00:00.000Z',
  },
  {
    id: 'diag_03',
    business_id: 'biz_01_health_bengaluru',
    problem_title: 'High Margin Skincare Opportunity (Kumkumadi Radiance)',
    problem_description: 'Kumkumadi Radiance Face Oil delivers a 66.2% gross margin and highest average order value (₹1,450), but receives only 15% of marketing visibility and digital ad budget.',
    category: 'pricing',
    evidence: 'Meta ad spend of ₹24,000 was split broadly, but skincare orders yielded 3.2x higher lifetime customer value (₹21,450 for VIPs) compared to single consultations.',
    confidence: 88,
    severity: 'opportunity',
    recommended_action: 'Create a 3-part Instagram Reel video series demonstrating authentic saffron infusion and pair Kumkumadi oil as an add-on during in-clinic facial rituals.',
    expected_kpi: '+35% increase in monthly skincare sales (approx +₹65,000 margin)',
    effort: 'medium',
    status: 'open',
    created_at: '2026-08-22T14:30:00.000Z',
  },
  {
    id: 'diag_04',
    business_id: 'biz_01_health_bengaluru',
    problem_title: 'Critical Stockout Risk on High-Velocity Formulations',
    problem_description: 'Moringa Capsules are currently out of stock (0 units) and Triphala Powder is down to 6 units. Reorder lead times from Kerala suppliers take 8 business days.',
    category: 'product_service',
    evidence: 'Triphala inventory is at 6 units with current burn rate of ~3 units/day, forecasting complete stockout within 48-72 hours.',
    confidence: 98,
    severity: 'critical',
    recommended_action: 'Immediately approve pending purchase order PO-VED-12 for 150 units with expedited courier delivery.',
    expected_kpi: 'Prevent ₹28,000 lost revenue over the coming 10-day cycle',
    effort: 'quick_win',
    status: 'open',
    created_at: '2026-08-24T09:00:00.000Z',
  },
];

export const SEED_DATA_SOURCES: DataSource[] = [
  {
    id: 'ds_01',
    business_id: 'biz_01_health_bengaluru',
    name: 'Tally / POS Export Q2-2026',
    source_type: 'pos_export',
    status: 'completed',
    record_count: 142,
    file_name: 'vedaveda_pos_orders_q2.csv',
    mapped_fields: { customer_name: 'Client Name', phone: 'Mobile', total_amount: 'Net Billed', date: 'Invoice Date' },
    imported_at: '2026-07-01T10:00:00.000Z',
  },
  {
    id: 'ds_02',
    business_id: 'biz_01_health_bengaluru',
    name: 'Instagram Inbound Leads July-August',
    source_type: 'csv',
    status: 'completed',
    record_count: 48,
    file_name: 'meta_leadgen_export_aug.csv',
    mapped_fields: { name: 'Full Name', email: 'Email', phone: 'Phone Number' },
    imported_at: '2026-08-15T12:00:00.000Z',
  },
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_01',
    business_id: 'biz_01_health_bengaluru',
    user_id: 'usr_founder',
    action: 'BUSINESS_INITIALIZED',
    details: 'Business Doctor AI workspace initialized with hybrid Ayurveda & Wellness model.',
    ip_address: '106.51.78.210',
    created_at: '2025-01-15T08:00:00.000Z',
  },
  {
    id: 'log_02',
    business_id: 'biz_01_health_bengaluru',
    user_id: 'usr_founder',
    action: 'DIAGNOSIS_RUN',
    details: 'Full diagnostic scan executed across 168 orders, 5 expenses, and 4 active inventory items.',
    ip_address: '106.51.78.210',
    created_at: '2026-08-24T18:00:00.000Z',
  },
];

export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp_01',
    business_id: 'biz_01_health_bengaluru',
    name: 'Monsoon Immunity & Sleep Reset WhatsApp Campaign',
    objective: 'increase_sales',
    target_segment: 'all',
    product_or_service_id: 'prod_01',
    product_or_service_name: 'Brahmi & Ashwagandha Deep Sleep Elixir (100ml)',
    offer: 'Buy 2 Deep Sleep Elixirs & get complimentary Triphala Detox Powder (₹450 value)',
    channel: 'whatsapp',
    start_date: '2026-08-01',
    end_date: '2026-08-15',
    message_content: 'Namaste {{name}}! Enhance your deep sleep and natural immunity this monsoon with our signature Brahmi & Ashwagandha Elixir. For the next 7 days, receive our Triphala Detox complimentary with every 2 bottles.',
    call_to_action: 'Reply "ELIXIR" to confirm your order with free delivery in Bengaluru.',
    status: 'executed',
    metrics: {
      leads_generated: 18,
      conversions: 12,
      customers_acquired: 5,
      revenue_attributed: 21576,
      repeat_purchases: 7,
      reactivation_results: 3,
      is_attribution_available: true,
    },
    approved_at: '2026-07-30T10:00:00.000Z',
    executed_at: '2026-08-01T09:00:00.000Z',
    created_at: '2026-07-28T14:30:00.000Z',
  },
  {
    id: 'camp_02',
    business_id: 'biz_01_health_bengaluru',
    name: 'Panchakarma Consultation Mid-Week Booster',
    objective: 'appointment_generation',
    target_segment: 'high_value',
    product_or_service_id: 'srv_01',
    product_or_service_name: 'Comprehensive Ayurvedic Nadi Pariksha & Consultation',
    offer: 'Complimentary 15-min Shirodhara head massage add-on with Tuesday-Thursday consultations',
    channel: 'whatsapp',
    start_date: '2026-08-20',
    end_date: '2026-08-31',
    message_content: 'Dear {{name}}, reserve your personalized Nadi Pariksha pulse diagnosis at VedaVeda Indiranagar this week and enjoy our complimentary Shirodhara relaxation add-on.',
    call_to_action: 'Reply to this message to book your preferred time slot with Dr. Gajendra.',
    status: 'approved',
    approved_at: '2026-08-19T11:00:00.000Z',
    created_at: '2026-08-18T16:00:00.000Z',
  },
  {
    id: 'camp_03',
    business_id: 'biz_01_health_bengaluru',
    name: 'Dormant VIP Win-Back Outreach Draft',
    objective: 'reactivate_customers',
    target_segment: 'dormant',
    product_or_service_id: 'prod_02',
    product_or_service_name: 'Kumkumadi Radiance Face Oil (30ml)',
    offer: 'Exclusive ₹350 VIP loyalty credit on your replenishment order this month',
    channel: 'whatsapp',
    start_date: '2026-09-01',
    end_date: '2026-09-10',
    message_content: 'Namaste {{name}}, we miss you at VedaVeda! To celebrate our upcoming autumn formulation batch, here is an exclusive ₹350 courtesy credit applied directly to your account.',
    call_to_action: 'Reply "REDEEM" to apply your ₹350 credit on your next order or clinic visit.',
    status: 'draft',
    created_at: '2026-08-25T09:15:00.000Z',
  },
];

